name: dotnet test
on:
  # Runs on pull requests.
  pull_request:

  # Runs on main branch updates.
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  # This event will only trigger a workflow run if the workflow file is on the default branch.

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - name: Test dotnet
        run: dotnet test --no-build
